<?php
/**
 * Created by PhpStorm.
 * User: ducho
 * Date: 5/2/2018
 * Time: 2:35 PM
 */

namespace App\Repositories\Eloquent;
use App\Repositories\PostRepositoryInterface;
use Illuminate\Support\Facades\DB;

class PostEloquentRepository extends BaseRepository implements PostRepositoryInterface
{
    /**
     * @return mixed
     */
    public function getModel()
    {
        return \App\post::class;
    }
    public function getDataTable()
    {
        // TODO: Implement getDataTable() method.
        return DB::table('post')->Join('users', 'users.id', '=', 'post.user_id')
            ->orderby('pubDate','asc')
            ->select('post.post_id','post.title','users.name')
            ->get();
    }

    public function baseDetails($id)
    {
        return parent::details($id); // TODO: Change the autogenerated stub
    }
    public function details($id)
    {
        $post = \app\post::all()->where('post_id','=',$id)->first()->toArray();
        $post['post_id']=$id;
        return $post;
    }
}